#pragma once

enum arm64_microarch {
  UNKNOWN,

  ARM_CORTEX_A32,
  ARM_CORTEX_A35,
  ARM_CORTEX_A53,
  ARM_CORTEX_A55,
  ARM_CORTEX_A57,
  ARM_CORTEX_A65,
  ARM_CORTEX_A65AE,
  ARM_CORTEX_A72,
  ARM_CORTEX_A73,
  ARM_CORTEX_A75,
  ARM_CORTEX_A76,
  ARM_CORTEX_A76AE,
  ARM_CORTEX_A77,
  ARM_CORTEX_A78,
  ARM_CORTEX_A78AE,
  ARM_CORTEX_A78C,
  ARM_CORTEX_A510,
  ARM_CORTEX_A710,
  ARM_CORTEX_X1,
  ARM_CORTEX_X1C,
  ARM_CORTEX_X2,
  ARM_NEOVERSE_E1,
  ARM_NEOVERSE_N1,
  ARM_NEOVERSE_N2,
  ARM_NEOVERSE_V1,

  CAVIUM_CN88XX,
  CAVIUM_CN99XX,

  QEMU_TCG,
};
