[project]
name = "moss"
version = "0.1.0"
description = "MOSS Microkernel Build Tools"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.23.0",
    "rich>=14.3.2",
]

[project.scripts]
build = "build:app"

[dependency-groups]
dev = [
    "cmake>=4.2.1",
    "cmake-format>=0.6.13",
    "ninja>=1.13.0",
]

[tool.uv]
package = true
