[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "moss-build"
version = "0.1.0"
description = "MOSS Microkernel Build Tools"
requires-python = ">=3.11"

[tool.uv]
dev-dependencies = [
    "cmake>=4.2.1",
]

[tool.uv.scripts]
configure = "cmake --preset"
build = "cmake --build"
clean = "cmake --build --target clean"