if (ARCH STREQUAL arm)
    set(MossArch arm)
elseif (ARCH STREQUAL arm64)
    set(MossArch arm64)
else ()
    message(STATUS "unexpected ARCH ${ARCH}, using default value \"arm64\"")
    set(MossArch arm64)
endif ()

message(STATUS "MossArch is ${MossArch}")
