function(find_asm_source_files OUT_asm_source_files IN_directory)
    file(GLOB_RECURSE asm_source_files LIST_DIRECTORIES false ${IN_directory}/*.S)
    set(${OUT_asm_source_files} ${asm_source_files} PARENT_SCOPE)
    message(STATUS "recurse found asm files: ${asm_source_files}")
endfunction()

function(find_asm_source_files_no_recurse OUT_asm_source_files IN_directory)
    file(GLOB asm_source_files LIST_DIRECTORIES false ${IN_directory}/*.S)
    set(${OUT_asm_source_files} ${asm_source_files} PARENT_SCOPE)
    message(STATUS "found asm files: ${asm_source_files}")
endfunction()
