function(install_git_hook IN_hook)
    set(git_hook_dir ${Moss_SOURCE_DIR}/.git/hooks)
    set(hook ${MOSS_SCRIPTS_DIR}/GitHooks/${IN_hook})
    if (NOT EXISTS ${git_hook_dir}/${IN_hook})
        file(COPY ${hook} DESTINATION ${git_hook_dir})
        message(STATUS "git hook ${IN_hook} installed")
    else ()
        file(MD5 ${git_hook_dir}/${IN_hook} git_hook_md5)
        message(STATUS "git hook ${IN_hook} md5: ${git_hook_md5}")
        file(MD5 ${hook} hook_md5)
        message(STATUS "hook ${IN_hook} md5: ${hook_md5}")
        if (NOT ${git_hook_md5} STREQUAL ${hook_md5})
            file(COPY ${hook} DESTINATION ${git_hook_dir})
            message(STATUS "git hook ${IN_hook} installed")
        endif ()
    endif ()
endfunction()

file(GLOB git_hooks ${MOSS_SCRIPTS_DIR}/GitHooks/*)
message(STATUS "git hooks: ${git_hooks}")
foreach (git_hook ${git_hooks})
    get_filename_component(file_name ${git_hook} NAME)
    install_git_hook(${file_name})
endforeach ()
