function(install_git_hook_commit_msg)
    set(git_hook_dir ${Moss_SOURCE_DIR}/.git/hooks)
    set(commit_msg ${MOSS_SCRIPTS_DIR}/GitHooks/commit-msg)
    if (NOT EXISTS ${git_hook_dir}/commit-msg)
        file(COPY ${commit_msg} DESTINATION ${git_hook_dir})
        message(STATUS "git hook commit msg installed")
    else ()
        file(MD5 ${git_hook_dir}/commit-msg git_hook_commit_msg_md5)
        message(STATUS "git_hook_commit_msg_md5: ${git_hook_commit_msg_md5}")
        file(MD5 ${commit_msg} hook_commit_msg_md5)
        message(STATUS "hook_commit_msg_md5: ${hook_commit_msg_md5}")
        if (NOT ${git_hook_commit_msg_md5} STREQUAL ${hook_commit_msg_md5})
            file(COPY ${commit_msg} DESTINATION ${git_hook_dir})
            message(STATUS "git hook commit msg installed")
        endif ()
    endif ()
endfunction()

install_git_hook_commit_msg()
