version: "3.7"

services:
  moss-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: moss
    ports:
      - "1234:1234"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/Moss
    privileged: true
    entrypoint:
      - /root/Moss/Scripts/Build/rpi3.build.sh

  moss-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: moss-build
    volumes:
      - ../:/root/Moss
    entrypoint:
      - /root/Moss/Scripts/Build/rpi3.build.sh

  moss-build-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: moss-build-alpine
    volumes:
      - ../:/root/Moss
    entrypoint:
      - /root/Moss/Scripts/Build/rpi3.build.sh

networks:
  os_share_network:
