FROM ubuntu:22.04

USER root

WORKDIR /root/Moss

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
        build-essential \
        binutils \
        clang \
        clang-tidy \
        lld \
        llvm \
        ninja-build \
        make \
        cmake \
        iwyu && \
    apt clean && \
    apt autoremove && \
    rm -rf /var/cache/apt/archives
