FROM ubuntu:22.04

# uncomment following line to speedup docker image build
COPY sshd_config /etc/ssh/sshd_config

USER root

WORKDIR /root/Moss

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
        gnupg \
        wget \
        build-essential \
        binutils \
        qemu-system-aarch64 \
        clang \
        clang-tidy \
        lld \
        llvm \
        gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu \
        gdb-multiarch \
        lldb \
        file \
        ninja-build \
        make \
        cmake \
        openssh-server \
        ssh \
        rsync \
        less \
        vim \
        git \
        zsh \
        autojump \
        iwyu && \
    apt clean && \
    apt autoremove && \
    rm -rf /var/cache/apt/archives

RUN mkdir /run/sshd && \
    yes password | passwd root && \
    echo 'password of root has been changed to "password"' && \
    echo 'set completion-ignore-case On' >> ~/.inputrc

RUN wget -P ~ https://git.io/.gdbinit
RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN echo "[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh" >> ~/.zshrc
RUN sed -i 's/plugins=(git)/plugins=(git autojump zsh-autosuggestions)/g' ~/.zshrc

CMD ["/usr/sbin/sshd", "-D"]
