version: "3.7"

services:
  moss:
    build:
      context: .
      dockerfile: Dockerfile
    image: moss
    ports:
      - "1234:1234"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/Moss
    privileged: true
    entrypoint:
      - /root/Moss/Scripts/BuildAndRun/rpi3.build.sh

networks:
  os_share_network:
