#!/usr/bin/env bash

Color_Off='\033[0m'
BRed="\033[1;31m"    # Red
BGreen="\033[1;32m"  # Green
BYellow="\033[1;33m" # Yellow
BBlue="\033[1;34m"   # Blue

MSG_FILE=$1
FILE_CONTENT="$(cat "$MSG_FILE")"
REGEX="\[.+\]\s.+"
ERROR_MSG="Commit message format must match regex \"${REGEX}\", for example: [xxx] yyy"

if grep -iqE "${REGEX}" "${MSG_FILE}"; then
  chco -e "${BGreen}Good commit!${Color_Off}\n"
else
  echo -e "${BRed}Bad commit message: ${BBlue}\"$FILE_CONTENT\"\n"
  echo -e "${BYellow}$ERROR_MSG\n"
  echo -e "commit-msg hook failed (add --no-verify to bypass)\n"

  exit 1
fi
exit 0
