name: Moss MacOS Build

on:
  schedule:
    - cron:  '* 12 * * 1' # every Monday 12:00AM UTC

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  pre-checks:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Check Commit Message
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(\[[\.\w\d\s_-]+\])+ .+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[abc] commit message."'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '14'
          check-path: 'SourceCode'
          fallback-style: 'LLVM' # optional

  build-on-mac:
    runs-on: macos-12
    needs:
      - pre-checks

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: brew install coreutils ninja qemu iwyu llvm

      - name: Build
        shell: bash
        run: export PATH="/usr/local/opt/llvm/bin:$PATH" && $GITHUB_WORKSPACE/Scripts/Build/rpi3.build.sh -c -t

      - uses: actions/upload-artifact@v3
        with:
          name: build-on-mac-${{env.BUILD_TYPE}}
          path: ${{runner.workspace}}/
