name: Moss MacOS Build

on:
  schedule:
    - cron:  '* 12 * * 1' # every Monday 12:00AM UTC

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-mac:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: brew install coreutils ninja qemu iwyu llvm

      - name: Build
        shell: bash
        run: export PATH="/usr/local/opt/llvm/bin:$PATH" && $GITHUB_WORKSPACE/Scripts/Build/rpi3.build.sh -c -t

      - uses: actions/upload-artifact@v3
        with:
          name: build-on-mac-${{env.BUILD_TYPE}}
          path: ${{runner.workspace}}/
